version: 2.1

jobs:
  test-and-build:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build

orbs:
  node: circleci/node@4.0.0

workflows:
  node-tests:
    jobs:
      - test-and-build
