import { Peer } from '../../interfaces'

export interface EditContainerMessageParams {
  /**
   * Message ID generated by bot, can be any string (max length - 255).
   * Bot will receive MessageIdAssigned update with localId - messageId match
   */
  localId?: string
  recipient: Peer
  content: any // TODO
}

export type EditContainerMessage = (params: EditContainerMessageParams) => Promise<{}>
