import { Peer } from '../../interfaces'
import { ContainerMessage } from '../../structures'

export interface SendContainerMessageParams {
  /**
   * Message ID generated by bot, can be any string (max length - 255).
   * Bot will receive MessageIdAssigned update with localId - messageId match
   */
  localId?: string
  recipient: Peer
  content: ContainerMessage
}

export type SendContainerMessage = (params: SendContainerMessageParams) => Promise<{}>
