import { Peer, InputMedia, InlineCommand, UiState } from '../../interfaces'
import { KeyboardBuilder, Media } from '../../structures'

export interface SendMessageParams {
  /**
   * Message ID generated by bot, can be any string (max length - 255).
   * Bot will receive MessageIdAssigned update with localId - messageId match
   */
  localId?: string
  /** Message ID to reply to */
  replyToMessageId?: string
  recipient: Peer
  /** Message text. Max length - 4096 */
  content: string
  uiState?: UiState
  inlineCommandRows?: InlineCommand[][] | KeyboardBuilder
  mediaList?: (InputMedia | Media)[]
}

/**
 * Use this method to send messages.
 *
 * If you specify localId, service will receive MessageIdAssigned
 * update with localId - messageId match
 */
export type SendMessage = (params: SendMessageParams) => Promise<{}>
